[project]
name = "captioner-translate"
version = "0.1.0"
description = "A subtitle translation tool using OpenAI API"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openai>=1.82.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "retry>=0.9.2",
]